name: Python CI

on:
  push:
    branches: [ "main" ]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Python script
        run: python3 helloworld.py
